"""initial tables

Revision ID: 5a0c1351cec2
Revises: 
Create Date: 2026-05-13 17:45:20.743115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0c1351cec2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_metrics', sa.Column('metric_type', sa.String(), nullable=False))
    op.add_column('portfolio_metrics', sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False))
    op.add_column('portfolio_metrics', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('portfolio_metrics', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('portfolio_metrics', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('uq_portfolio_metrics_window'), 'portfolio_metrics', type_='unique')
    op.create_index('idx_portfolio_metrics_type', 'portfolio_metrics', ['metric_type'], unique=False)
    op.create_unique_constraint('uq_portfolio_metric_window', 'portfolio_metrics', ['portfolio_id', 'metric_type', 'start_date', 'end_date'])
    op.drop_column('portfolio_metrics', 'end_value')
    op.drop_column('portfolio_metrics', 'start_value')
    op.drop_column('portfolio_metrics', 'cagr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_metrics', sa.Column('cagr', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=False))
    op.add_column('portfolio_metrics', sa.Column('start_value', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False))
    op.add_column('portfolio_metrics', sa.Column('end_value', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False))
    op.drop_constraint('uq_portfolio_metric_window', 'portfolio_metrics', type_='unique')
    op.drop_index('idx_portfolio_metrics_type', table_name='portfolio_metrics')
    op.create_unique_constraint(op.f('uq_portfolio_metrics_window'), 'portfolio_metrics', ['portfolio_id', 'start_date', 'end_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('portfolio_metrics', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('portfolio_metrics', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('portfolio_metrics', 'extra_data')
    op.drop_column('portfolio_metrics', 'value')
    op.drop_column('portfolio_metrics', 'metric_type')
    # ### end Alembic commands ###
